### ISSUE TITLE
将 Java 的渲染代码移动到本机的方式？

### ISSUE THREAD

**Issue by zyowo** [ywwynm/AndroidPractice#1]
大神好！感谢您提供 Unity 渲染 Android 图像的方案。这几天阅读了您的文章 
https://stackoverflow.com/questions/52088859/opengl-drawing-on-android-combining-with-unity-to-transfer-texture-through-frame

目前我正在制作基于 UVC 相机的 Unity 游戏，需要在 Unity 中获取 外接相机的图像。由于之前用的 Java 在 主线程上渲染，所以出现了红屏等问题，也无法使用多线程渲染。现在需要将渲染移动到本机代码。

我查阅了 google VR SDK，发现调用渲染的方式有些不同，是直接 Unity -> extern -> AAR 里面的 C++ 代码。另外 FaceUnity 的 SDK 也使用的是这种方法。

而大神这边用的是我比较顺手的 Unity -> 调用 Java 方法 -> 转到 native 接口 -> 再通过 JNI 调用 C++ 代码。

想请教一下，这两种调用方法，有什么区别和优缺点？

**Comment by ywwynm** [comment]
@zyowo 我没有研究过Google或者FaceUnity的SDK，不太清楚你说的 Unity -> extern -> AAR 是个什么样子的流程。可以描述一下么？

**Comment by zyowo** [comment]
我今天刚在研究，抱歉描述不太准确。

首先在 C++ 本机代码层，[gvrvideo_unity.cc](https://github.com/googlevr/gvr-unity-sdk/blob/master/native_libs/gvr-exoplayersupport/src/main/cpp/gvrvideo_unity.cc)

提供 Unity 需要的渲染的接口为：
```c++
// GetRenderEventFunc, an example function we export which is used to get a
// rendering event callback function.
UnityRenderingEvent GetRenderEventFunc() { return OnRenderEvent; }
```

此处写法与 [Unity本机插件文档](https://docs.unity3d.com/cn/current/Manual/NativePluginInterface.html) 类似。

该代码与 Java 代码一起打包成了 gvr-exoplayersupport-release.aar，并导入 Unity 中

然后在 [GvrVideoPlayerTexture.cs](https://github.com/googlevr/gvr-unity-sdk/blob/master/Assets/GoogleVR/Scripts/Video/GvrVideoPlayerTexture.cs)，定义了 extern 的静态方法：
```c#
#if UNITY_ANDROID && !UNITY_EDITOR

    [DllImport(DLL_NAME)]
    private static extern IntPtr GetRenderEventFunc();
#endif
```
其中 `DLL_NAME` 为 `private const string DLL_NAME = "gvrvideo";`

业务中直接使用了该方法，调用了 AAR 里面的 C++ 代码如下。

```c#
    /// <summary>Issues the player event.</summary>
    /// <param name="evt">The event to send to the video player instance.</param>
    private void IssuePlayerEvent(RenderCommand evt)
    {
        if (renderEventFunction == IntPtr.Zero)
        {
            renderEventFunction = GetRenderEventFunc();
        }

        if (renderEventFunction == IntPtr.Zero || evt == RenderCommand.None)
        {
            Debug.LogError("Attempt to IssuePlayerEvent before renderEventFunction ready.");
            return;
        }

        GL.IssuePluginEvent(renderEventFunction, videoPlayerEventBase + (int)evt);
    }
```

因为没有使用任何  AndroidJavaObject ，所以我称之为 Unity -> extern -> AAR 的流程。

**Comment by ywwynm** [comment]
看上去是直接使用了C#的native函数调用机制，我也是第一次见到。从性能上来说，应该会比AndroidJavaObject的那种形式要快，但是我觉得对于一般的app来说可能不需要特别在意吧。

**Comment by zyowo** [comment]
好吧，我又研究了一天 Google VR SDK，发现到了 C++ 层后，还是要通过 JNI 去生成 Java 的 `VideoPlayer` 实例，更新 `SurfaceTexture`，然后再渲染的。

Unity、Java、C++，三者还是需要互相交互，只是顺序不一样。

我的 相机库是直接用 `AndroidJavaObject` 实例化的，给 C++ 渲染代码输入图像好像挺麻烦。

如果按照您文章的写法：
```c#
void Update() {
  // call SurfaceTexture.updateTexImage in plugin
  IssuePluginEvent(2); // let's assume 2 stands for transferring TEXTURE_EXTERNAL_OES to TEXTURE_2D through FrameBuffer
  // call Texture2D.UpdateExternalTexture to update GameObject's appearance
}
```
先在主线程调用 相机库实例，更新输入图像，
然后渲染，访问数据的工作就简单一些。先按您的路线写写看。

**Comment by zyowo** [comment]
上述写法出现了一个问题，请大神赐教：

根据 Android 官方文档介绍：

[SurfaceTexture](https://developer.android.com/reference/android/graphics/SurfaceTexture)

> SurfaceTexture objects may be created on any thread. updateTexImage() may only be called on the thread with the OpenGL ES context that contains the texture object.

Unity 开启多线程后， Update 线程并非渲染线程，因此在 Update() 中调用 SurfaceTexture.updateTexImage 是无效的。

请问大神在制作 Unity JNI 的时候遇到这样的问题了吗？是如何解决的？

必须 用 IssuePluginEvent 渲染线程 转到 C++ 代码，然后通过 JNI 再 转到 Java 代码，然后调用 updateTexImage？

**Comment by zyowo** [comment]
BTW, 也许我应该在正规的网站上问这些问题，而不是错误使用 Github Issue，为此感到抱歉 :(

**Comment by ywwynm** [comment]
@zyowo 必须使用IssuePluginEvent调用C++代码，但是之后可以直接在C++代码中获得java层的SurfaceTexture对象，进而可以在C++层调用updateTexImage。
另外，我其实不是很建议在这个时候开启unity的多线程渲染，因为为了在C++中调用updateTexImage，必须将jvm attach到当前的线程，而这个操作是需要一定开销的，会影响帧率（比如要实现60FPS的视频播放，这个操作就有可能产生卡顿和跳帧）。

**Comment by zyowo** [comment]
感谢回复，我已经完成了

> 设置 SurfaceTexture 给 Java，然后在 IssuePluginEvent 时 attach 线程并更新纹理

这样的流程。可能确实会影响帧率，我去查了一下 Google 的写法，也是类似：

[Google GVR SDK 更新视频纹理](https://github.com/googlevr/gvr-unity-sdk/blob/f999ed727a1d238c246ba4a504b77d55b59c9e9a/native_libs/gvr-exoplayersupport/src/main/cpp/video_player_impl.cc#L297)

估计也是无奈之举。
我这里的业务，会同时出现 AVPro 播放视频 和相机库渲染，不开多线程渲染只有 11帧左右。
只能先尝试一下。🤦‍
